version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - FINNHUB_API_TOKEN=${FINNHUB_API_TOKEN}
      - SYMBOLS=${SYMBOLS}

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=stocks
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
