version: "3.8"

services:
  app:
    build: .
    container_name: app
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_NAME=${MONGO_DB}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - FINNHUB_API_TOKEN=${FINNHUB_API_TOKEN}
      - SYMBOLS=${SYMBOLS}
    env_file:
      - .env

  mongo:
    image: mongo:7.0.14
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "nats", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  mongo-data:
