spring:
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/stocks?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#logging:
#  level:
#    org.springframework.data.mongodb: DEBUG
#    org.mongodb.driver: DEBUG
