spring:
  application:
    name: stockanalyzer
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
api:
  finnhub:
    token: ${FINNHUB_API_TOKEN}
    symbols: ${SYMBOLS}

logExecutionTime:
  enabled: true
