spring:
  application:
    name: stockanalyzer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stocksDb
api:
  finnhub:
    token: ${FINNHUB_API_TOKEN}
    symbols: ${SYMBOLS}

logExecutionTime:
  enabled: true
