spring:
  application:
    name: stockanalyzer
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/stocks?authSource=admin
api:
  finnhub:
    token: ${FINNHUB_API_TOKEN}
    symbols: ${SYMBOLS}

logExecutionTime:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
