spring:
  application:
    name: stockanalyzer
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/stocks
api:
  finnhub:
    token: ${FINNHUB_API_TOKEN}
    symbols: ${SYMBOLS}

logExecutionTime:
  enabled: true
