[versions]
kotlin = "1.9.23"
spring-boot = "3.3.2"
dependency-management = "1.1.6"
detekt = "1.23.6"
springmockk = "4.0.2"
mockito-kotlin = "3.2.0"
finnhub-kotlin-client = "2.0.20"
mongock = "5.2.4"
shedlock = "5.16.0"
ktlint = "1.23.6"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
finnhub-kotlin-client = { group = "io.finnhub", name = "kotlin-client", version.ref = "finnhub-kotlin-client" }
mongock-springboot-v3 = { group = "io.mongock", name = "mongock-springboot-v3", version.ref = "mongock" }
mongock-mongodb-springdata-v4-driver = { group = "io.mongock", name = "mongodb-springdata-v4-driver", version.ref = "mongock" }
shedlock-spring = { group = "net.javacrumbs.shedlock", name = "shedlock-spring", version.ref = "shedlock" }
shedlock-provider-mongo = { group = "net.javacrumbs.shedlock", name = "shedlock-provider-mongo", version.ref = "shedlock" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "ktlint" }
spring-mockk = { group = "com.ninja-squad", name = "springmockk", version.ref = "springmockk" }
