logExecutionTime:
  enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/stocks?authSource=admin
  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 10000
        max.poll.interval.ms: 10000
    bootstrap-servers: http://localhost:9092

logging.level.org.springframework.test.context.cache: debug
